-- MySQL Script generated by MySQL Workbench
-- Tue Jan 16 14:52:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bind_conf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bind_conf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bind_conf` DEFAULT CHARACTER SET utf8 ;
USE `bind_conf` ;

-- -----------------------------------------------------
-- Table `bind_conf`.`dns_forward_zone_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`dns_forward_zone_grp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `typ` VARCHAR(16) NOT NULL DEFAULT 'only',
  `disabled` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dm_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bind_conf`.`ldns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`ldns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `addr` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bind_conf`.`dns_forward_ipnet_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`dns_forward_ipnet_grp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `prio` INT NOT NULL DEFAULT 10,
  `disabled` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bind_conf`.`dns_forwarders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`dns_forwarders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zone_grp_id` INT NOT NULL,
  `ipnet_grp_id` INT NOT NULL,
  `ldns_id` INT NOT NULL,
  `disabled` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `zone_id_idx` (`zone_grp_id` ASC),
  INDEX `ldns_id_idx` (`ldns_id` ASC),
  INDEX `ipnet_grp_id_idx` (`ipnet_grp_id` ASC),
  CONSTRAINT `fk_fw_zone_grp_id`
    FOREIGN KEY (`zone_grp_id`)
    REFERENCES `bind_conf`.`dns_forward_zone_grp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fw_ldns_id`
    FOREIGN KEY (`ldns_id`)
    REFERENCES `bind_conf`.`ldns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fw_ipnet_grp_id`
    FOREIGN KEY (`ipnet_grp_id`)
    REFERENCES `bind_conf`.`dns_forward_ipnet_grp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bind_conf`.`dns_forward_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`dns_forward_zone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NOT NULL DEFAULT 'only',
  `grp_id` INT NOT NULL,
  `disabled` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `grp_id_idx` (`grp_id` ASC),
  CONSTRAINT `fk_zone_grp_id`
    FOREIGN KEY (`grp_id`)
    REFERENCES `bind_conf`.`dns_forward_zone_grp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bind_conf`.`dns_forward_ipnet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bind_conf`.`dns_forward_ipnet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ipnet` VARCHAR(45) NULL,
  `disabled` TINYINT(4) NULL,
  `grp_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `grp_id_idx` (`grp_id` ASC),
  CONSTRAINT `fk_ipnet_grp_id`
    FOREIGN KEY (`grp_id`)
    REFERENCES `bind_conf`.`dns_forward_ipnet_grp` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
