-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 16:20:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `iwg`.`dns_forward_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwg`.`dns_forward_zone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dm` VARCHAR(255) NULL,
  `typ` VARCHAR(16) NOT NULL DEFAULT 'only',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dm_UNIQUE` (`dm` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `iwg`.`dns_forwarders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwg`.`dns_forwarders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zone_id` INT NULL,
  `ldns_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `zone_id_idx` (`zone_id` ASC),
  INDEX `ldns_id_idx` (`ldns_id` ASC),
  CONSTRAINT `zone_id`
    FOREIGN KEY (`zone_id`)
    REFERENCES `iwg`.`dns_forward_zone` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ldns_id`
    FOREIGN KEY (`ldns_id`)
    REFERENCES `iwg`.`ldns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  UNIQUE INDEX `zone_forwarder_UNIQUE` (`zone_id` ASC, `ldns_id` ASC))
ENGINE = InnoDB;

CREATE or replace VIEW `dns_forward_view` AS
select dns_forward_zone.id as zone_id, dns_forward_zone.dm, dns_forward_zone.typ as forward_typ, ldns.name as ldns_name,
ldns.addr as ldns_addr
from dns_forward_zone, dns_forwarders, ldns
where ldns.id = dns_forwarders.ldns_id and dns_forward_zone.id = dns_forwarders.zone_id

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
